export default {
    bg: require("./bg.png"),
    imageButton: require("./imageButton.png"),
    verify_product: require("./verify_product.png"),
    s1: require("./scan/s1.png"),
    s2: require("./scan/s2.png"),
    s3: require("./scan/s3.png"),
    s4: require("./scan/s4.png"),
    s5: require("./scan/s5.png"),
    s6: require("./scan/s6.png"),
    Frame: require("./Frame.png"),
    RedFrame: require("./RedFrame.png"),
    RedFrame2: require("./RedFrame2.png"),
    scanner: require("./scanner.png"),
    authentic: require("./authentic.png"),
    backBtnBg: require("./backBtnBg.png"),
    logout: require("./logout.png"),
}